/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type ExecutorConfigStruct = { module: AddressLike; data: BytesLike };

export type ExecutorConfigStructOutput = [module: string, data: string] & {
  module: string;
  data: string;
};

export type FallbackConfigStruct = { module: AddressLike; data: BytesLike };

export type FallbackConfigStructOutput = [module: string, data: string] & {
  module: string;
  data: string;
};

export type HookConfigStruct = { module: AddressLike; data: BytesLike };

export type HookConfigStructOutput = [module: string, data: string] & {
  module: string;
  data: string;
};

export type ValidationConfigStruct = { module: AddressLike; data: BytesLike };

export type ValidationConfigStructOutput = [module: string, data: string] & {
  module: string;
  data: string;
};

export type RegistryConfigStruct = {
  registry: AddressLike;
  attesters: AddressLike[];
  threshold: BigNumberish;
};

export type RegistryConfigStructOutput = [
  registry: string,
  attesters: string[],
  threshold: bigint
] & { registry: string; attesters: string[]; threshold: bigint };

export interface INexusBootstrapInterface extends Interface {
  getFunction(
    nameOrSignature: "initNexusWithDefaultValidatorAndOtherModules"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "initNexusWithDefaultValidatorAndOtherModules",
    values: [
      AddressLike,
      AddressLike[],
      ExecutorConfigStruct[],
      FallbackConfigStruct,
      HookConfigStruct[],
      ValidationConfigStruct[],
      RegistryConfigStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "initNexusWithDefaultValidatorAndOtherModules",
    data: BytesLike
  ): Result;
}

export interface INexusBootstrap extends BaseContract {
  connect(runner?: ContractRunner | null): INexusBootstrap;
  waitForDeployment(): Promise<this>;

  interface: INexusBootstrapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  initNexusWithDefaultValidatorAndOtherModules: TypedContractMethod<
    [
      owner: AddressLike,
      validators: AddressLike[],
      executors: ExecutorConfigStruct[],
      fallbackConfig: FallbackConfigStruct,
      hooks: HookConfigStruct[],
      validationConfigs: ValidationConfigStruct[],
      registryConfig: RegistryConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "initNexusWithDefaultValidatorAndOtherModules"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      validators: AddressLike[],
      executors: ExecutorConfigStruct[],
      fallbackConfig: FallbackConfigStruct,
      hooks: HookConfigStruct[],
      validationConfigs: ValidationConfigStruct[],
      registryConfig: RegistryConfigStruct
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
