/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as autoBridgeSol from "./AutoBridge.sol";
export type { autoBridgeSol };
import type * as autoEarnSol from "./AutoEarn.sol";
export type { autoEarnSol };
import type * as autoSwapSol from "./AutoSwap.sol";
export type { autoSwapSol };
export type { BondModule } from "./BondModule";
