/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INexusAccountFactory,
  INexusAccountFactoryInterface,
} from "../INexusAccountFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initData",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "computeAccountAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initData",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "createAccount",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INexusAccountFactory__factory {
  static readonly abi = _abi;
  static createInterface(): INexusAccountFactoryInterface {
    return new Interface(_abi) as INexusAccountFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INexusAccountFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as INexusAccountFactory;
  }
}
