/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBiconomyMetaFactory,
  IBiconomyMetaFactoryInterface,
} from "../IBiconomyMetaFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "factoryData",
        type: "bytes",
      },
    ],
    name: "deployWithFactory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBiconomyMetaFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IBiconomyMetaFactoryInterface {
    return new Interface(_abi) as IBiconomyMetaFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBiconomyMetaFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBiconomyMetaFactory;
  }
}
