/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccount } from "./IAccount";
export type { IAccountLocker } from "./IAccountLocker";
export type { MockResourceLockPreValidationHook } from "./MockResourceLockPreValidationHook";
