/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iComposableExecutionSol from "./IComposableExecution.sol";
export type { iComposableExecutionSol };
