/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INexusBootstrap,
  INexusBootstrapInterface,
} from "../../../contracts/interfaces.sol/INexusBootstrap";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "validators",
        type: "address[]",
      },
      {
        components: [
          {
            internalType: "address",
            name: "module",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct ExecutorConfig[]",
        name: "executors",
        type: "tuple[]",
      },
      {
        components: [
          {
            internalType: "address",
            name: "module",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct FallbackConfig",
        name: "fallbackConfig",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "module",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct HookConfig[]",
        name: "hooks",
        type: "tuple[]",
      },
      {
        components: [
          {
            internalType: "address",
            name: "module",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct ValidationConfig[]",
        name: "validationConfigs",
        type: "tuple[]",
      },
      {
        components: [
          {
            internalType: "address",
            name: "registry",
            type: "address",
          },
          {
            internalType: "address[]",
            name: "attesters",
            type: "address[]",
          },
          {
            internalType: "uint256",
            name: "threshold",
            type: "uint256",
          },
        ],
        internalType: "struct RegistryConfig",
        name: "registryConfig",
        type: "tuple",
      },
    ],
    name: "initNexusWithDefaultValidatorAndOtherModules",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INexusBootstrap__factory {
  static readonly abi = _abi;
  static createInterface(): INexusBootstrapInterface {
    return new Interface(_abi) as INexusBootstrapInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INexusBootstrap {
    return new Contract(address, _abi, runner) as unknown as INexusBootstrap;
  }
}
