/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IBiconomyMetaFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBiconomyMetaFactory__factory>;
    getContractFactory(
      name: "IBondModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBondModule__factory>;
    getContractFactory(
      name: "IMockToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMockToken__factory>;
    getContractFactory(
      name: "IMulticall3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMulticall3__factory>;
    getContractFactory(
      name: "INexusAccountFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexusAccountFactory__factory>;
    getContractFactory(
      name: "INexusBootstrap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexusBootstrap__factory>;

    getContractAt(
      name: "IBiconomyMetaFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBiconomyMetaFactory>;
    getContractAt(
      name: "IBondModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBondModule>;
    getContractAt(
      name: "IMockToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMockToken>;
    getContractAt(
      name: "IMulticall3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMulticall3>;
    getContractAt(
      name: "INexusAccountFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexusAccountFactory>;
    getContractAt(
      name: "INexusBootstrap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexusBootstrap>;

    deployContract(
      name: "IBiconomyMetaFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBiconomyMetaFactory>;
    deployContract(
      name: "IBondModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBondModule>;
    deployContract(
      name: "IMockToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMockToken>;
    deployContract(
      name: "IMulticall3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMulticall3>;
    deployContract(
      name: "INexusAccountFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusAccountFactory>;
    deployContract(
      name: "INexusBootstrap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusBootstrap>;

    deployContract(
      name: "IBiconomyMetaFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBiconomyMetaFactory>;
    deployContract(
      name: "IBondModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBondModule>;
    deployContract(
      name: "IMockToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMockToken>;
    deployContract(
      name: "IMulticall3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMulticall3>;
    deployContract(
      name: "INexusAccountFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusAccountFactory>;
    deployContract(
      name: "INexusBootstrap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusBootstrap>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
