/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1967__factory>;
    getContractFactory(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267__factory>;
    getContractFactory(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBeacon__factory>;
    getContractFactory(
      name: "ERC1967Utils",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1967Utils__factory>;
    getContractFactory(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Proxy__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Permit__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "Address",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Address__factory>;
    getContractFactory(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECDSA__factory>;
    getContractFactory(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeCast__factory>;
    getContractFactory(
      name: "Nonces",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nonces__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShortStrings__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "BasePaymaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasePaymaster__factory>;
    getContractFactory(
      name: "EntryPoint",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EntryPoint__factory>;
    getContractFactory(
      name: "NonceManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NonceManager__factory>;
    getContractFactory(
      name: "SenderCreator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SenderCreator__factory>;
    getContractFactory(
      name: "StakeManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakeManager__factory>;
    getContractFactory(
      name: "UserOperationLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UserOperationLib__factory>;
    getContractFactory(
      name: "IAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccount__factory>;
    getContractFactory(
      name: "IAccountExecute",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccountExecute__factory>;
    getContractFactory(
      name: "IAggregator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAggregator__factory>;
    getContractFactory(
      name: "IEntryPoint",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEntryPoint__factory>;
    getContractFactory(
      name: "INonceManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INonceManager__factory>;
    getContractFactory(
      name: "IPaymaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPaymaster__factory>;
    getContractFactory(
      name: "IStakeManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStakeManager__factory>;
    getContractFactory(
      name: "VerifyingPaymaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VerifyingPaymaster__factory>;
    getContractFactory(
      name: "ComposableExecutionBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComposableExecutionBase__factory>;
    getContractFactory(
      name: "ComposableExecutionLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComposableExecutionLib__factory>;
    getContractFactory(
      name: "IComposableExecution",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IComposableExecution__factory>;
    getContractFactory(
      name: "IComposableExecutionModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IComposableExecutionModule__factory>;
    getContractFactory(
      name: "Storage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Storage__factory>;
    getContractFactory(
      name: "BaseAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BaseAccount__factory>;
    getContractFactory(
      name: "ExecutionHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExecutionHelper__factory>;
    getContractFactory(
      name: "ModuleManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ModuleManager__factory>;
    getContractFactory(
      name: "RegistryAdapter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RegistryAdapter__factory>;
    getContractFactory(
      name: "Stakeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Stakeable__factory>;
    getContractFactory(
      name: "BiconomyMetaFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BiconomyMetaFactory__factory>;
    getContractFactory(
      name: "K1ValidatorFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.K1ValidatorFactory__factory>;
    getContractFactory(
      name: "NexusAccountFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NexusAccountFactory__factory>;
    getContractFactory(
      name: "IBiconomyMetaFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBiconomyMetaFactory__factory>;
    getContractFactory(
      name: "IBondModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBondModule__factory>;
    getContractFactory(
      name: "IMockToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMockToken__factory>;
    getContractFactory(
      name: "IMulticall3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMulticall3__factory>;
    getContractFactory(
      name: "INexusAccountFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexusAccountFactory__factory>;
    getContractFactory(
      name: "INexusBootstrap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexusBootstrap__factory>;
    getContractFactory(
      name: "IAccountConfig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccountConfig__factory>;
    getContractFactory(
      name: "IBaseAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBaseAccount__factory>;
    getContractFactory(
      name: "IBaseAccountEventsAndErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBaseAccountEventsAndErrors__factory>;
    getContractFactory(
      name: "IExecutionHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IExecutionHelper__factory>;
    getContractFactory(
      name: "IExecutionHelperEventsAndErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IExecutionHelperEventsAndErrors__factory>;
    getContractFactory(
      name: "IModuleManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IModuleManager__factory>;
    getContractFactory(
      name: "IModuleManagerEventsAndErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IModuleManagerEventsAndErrors__factory>;
    getContractFactory(
      name: "IStakeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStakeable__factory>;
    getContractFactory(
      name: "INexusFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexusFactory__factory>;
    getContractFactory(
      name: "IERC4337Account",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC4337Account__factory>;
    getContractFactory(
      name: "IERC7484",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC7484__factory>;
    getContractFactory(
      name: "IERC7579Account",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC7579Account__factory>;
    getContractFactory(
      name: "IMulticall3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMulticall3__factory>;
    getContractFactory(
      name: "INexus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexus__factory>;
    getContractFactory(
      name: "INexusEventsAndErrors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INexusEventsAndErrors__factory>;
    getContractFactory(
      name: "IExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IExecutor__factory>;
    getContractFactory(
      name: "IFallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFallback__factory>;
    getContractFactory(
      name: "IHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHook__factory>;
    getContractFactory(
      name: "IModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IModule__factory>;
    getContractFactory(
      name: "IPreValidationHookERC1271",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPreValidationHookERC1271__factory>;
    getContractFactory(
      name: "IPreValidationHookERC4337",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPreValidationHookERC4337__factory>;
    getContractFactory(
      name: "IValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IValidator__factory>;
    getContractFactory(
      name: "AssociatedArrayLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AssociatedArrayLib__factory>;
    getContractFactory(
      name: "EnumerableMap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EnumerableMap__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "ProxyLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProxyLib__factory>;
    getContractFactory(
      name: "Counter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Counter__factory>;
    getContractFactory(
      name: "EmittingHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EmittingHook__factory>;
    getContractFactory(
      name: "ExposedNexus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExposedNexus__factory>;
    getContractFactory(
      name: "IExposedNexus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IExposedNexus__factory>;
    getContractFactory(
      name: "Mock7739PreValidationHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Mock7739PreValidationHook__factory>;
    getContractFactory(
      name: "MockAccountLocker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockAccountLocker__factory>;
    getContractFactory(
      name: "MockCallee",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCallee__factory>;
    getContractFactory(
      name: "MockDelegateTarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDelegateTarget__factory>;
    getContractFactory(
      name: "MockExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockExecutor__factory>;
    getContractFactory(
      name: "MockHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHandler__factory>;
    getContractFactory(
      name: "MockHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHook__factory>;
    getContractFactory(
      name: "MockInvalidModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockInvalidModule__factory>;
    getContractFactory(
      name: "MockMultiModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockMultiModule__factory>;
    getContractFactory(
      name: "MockERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC1155__factory>;
    getContractFactory(
      name: "MockNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockNFT__factory>;
    getContractFactory(
      name: "MockPaymaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockPaymaster__factory>;
    getContractFactory(
      name: "MockPreValidationHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockPreValidationHook__factory>;
    getContractFactory(
      name: "MockPreValidationHookMultiplexer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockPreValidationHookMultiplexer__factory>;
    getContractFactory(
      name: "MockRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockRegistry__factory>;
    getContractFactory(
      name: "IAccount",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccount__factory>;
    getContractFactory(
      name: "IAccountLocker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccountLocker__factory>;
    getContractFactory(
      name: "MockResourceLockPreValidationHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockResourceLockPreValidationHook__factory>;
    getContractFactory(
      name: "MockSafe1271Caller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockSafe1271Caller__factory>;
    getContractFactory(
      name: "MockSimpleValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockSimpleValidator__factory>;
    getContractFactory(
      name: "MockTarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockTarget__factory>;
    getContractFactory(
      name: "MockToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockToken__factory>;
    getContractFactory(
      name: "MockTransferer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockTransferer__factory>;
    getContractFactory(
      name: "MockValidator_7739v2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockValidator_7739v2__factory>;
    getContractFactory(
      name: "MockValidator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockValidator__factory>;
    getContractFactory(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1271__factory>;
    getContractFactory(
      name: "TokenWithPermit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenWithPermit__factory>;
    getContractFactory(
      name: "AutoBridgeModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AutoBridgeModule__factory>;
    getContractFactory(
      name: "ISpokePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISpokePool__factory>;
    getContractFactory(
      name: "IWrappedNative",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWrappedNative__factory>;
    getContractFactory(
      name: "AutoEarn",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AutoEarn__factory>;
    getContractFactory(
      name: "IAavePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAavePool__factory>;
    getContractFactory(
      name: "IWrappedNative",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWrappedNative__factory>;
    getContractFactory(
      name: "AutoSwapModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AutoSwapModule__factory>;
    getContractFactory(
      name: "IQuoterV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IQuoterV2__factory>;
    getContractFactory(
      name: "ISwapRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISwapRouter__factory>;
    getContractFactory(
      name: "IWrappedNative",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWrappedNative__factory>;
    getContractFactory(
      name: "BondModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BondModule__factory>;
    getContractFactory(
      name: "K1Validator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.K1Validator__factory>;
    getContractFactory(
      name: "Nexus",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Nexus__factory>;
    getContractFactory(
      name: "NexusBootstrap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NexusBootstrap__factory>;
    getContractFactory(
      name: "NexusProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NexusProxy__factory>;
    getContractFactory(
      name: "ERC7739Validator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC7739Validator__factory>;
    getContractFactory(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC5267__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC4626",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC4626__factory>;
    getContractFactory(
      name: "SentinelListLib",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SentinelListLib__factory>;
    getContractFactory(
      name: "LibEIP7702",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibEIP7702__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "CallContextChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CallContextChecker__factory>;
    getContractFactory(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ECDSA__factory>;
    getContractFactory(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP712__factory>;
    getContractFactory(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.UUPSUpgradeable__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1967",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1967>;
    getContractAt(
      name: "IERC5267",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267>;
    getContractAt(
      name: "IBeacon",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBeacon>;
    getContractAt(
      name: "ERC1967Utils",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1967Utils>;
    getContractAt(
      name: "Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Proxy>;
    getContractAt(
      name: "ERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "IERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Permit>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "Address",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Address>;
    getContractAt(
      name: "ECDSA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ECDSA>;
    getContractAt(
      name: "EIP712",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712>;
    getContractAt(
      name: "Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "SafeCast",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeCast>;
    getContractAt(
      name: "Nonces",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Nonces>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "ShortStrings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ShortStrings>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "BasePaymaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BasePaymaster>;
    getContractAt(
      name: "EntryPoint",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EntryPoint>;
    getContractAt(
      name: "NonceManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NonceManager>;
    getContractAt(
      name: "SenderCreator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SenderCreator>;
    getContractAt(
      name: "StakeManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakeManager>;
    getContractAt(
      name: "UserOperationLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UserOperationLib>;
    getContractAt(
      name: "IAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccount>;
    getContractAt(
      name: "IAccountExecute",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccountExecute>;
    getContractAt(
      name: "IAggregator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAggregator>;
    getContractAt(
      name: "IEntryPoint",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEntryPoint>;
    getContractAt(
      name: "INonceManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INonceManager>;
    getContractAt(
      name: "IPaymaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPaymaster>;
    getContractAt(
      name: "IStakeManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStakeManager>;
    getContractAt(
      name: "VerifyingPaymaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VerifyingPaymaster>;
    getContractAt(
      name: "ComposableExecutionBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ComposableExecutionBase>;
    getContractAt(
      name: "ComposableExecutionLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ComposableExecutionLib>;
    getContractAt(
      name: "IComposableExecution",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IComposableExecution>;
    getContractAt(
      name: "IComposableExecutionModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IComposableExecutionModule>;
    getContractAt(
      name: "Storage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Storage>;
    getContractAt(
      name: "BaseAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BaseAccount>;
    getContractAt(
      name: "ExecutionHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExecutionHelper>;
    getContractAt(
      name: "ModuleManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ModuleManager>;
    getContractAt(
      name: "RegistryAdapter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RegistryAdapter>;
    getContractAt(
      name: "Stakeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Stakeable>;
    getContractAt(
      name: "BiconomyMetaFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BiconomyMetaFactory>;
    getContractAt(
      name: "K1ValidatorFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.K1ValidatorFactory>;
    getContractAt(
      name: "NexusAccountFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NexusAccountFactory>;
    getContractAt(
      name: "IBiconomyMetaFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBiconomyMetaFactory>;
    getContractAt(
      name: "IBondModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBondModule>;
    getContractAt(
      name: "IMockToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMockToken>;
    getContractAt(
      name: "IMulticall3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMulticall3>;
    getContractAt(
      name: "INexusAccountFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexusAccountFactory>;
    getContractAt(
      name: "INexusBootstrap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexusBootstrap>;
    getContractAt(
      name: "IAccountConfig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccountConfig>;
    getContractAt(
      name: "IBaseAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBaseAccount>;
    getContractAt(
      name: "IBaseAccountEventsAndErrors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IBaseAccountEventsAndErrors>;
    getContractAt(
      name: "IExecutionHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IExecutionHelper>;
    getContractAt(
      name: "IExecutionHelperEventsAndErrors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IExecutionHelperEventsAndErrors>;
    getContractAt(
      name: "IModuleManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IModuleManager>;
    getContractAt(
      name: "IModuleManagerEventsAndErrors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IModuleManagerEventsAndErrors>;
    getContractAt(
      name: "IStakeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IStakeable>;
    getContractAt(
      name: "INexusFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexusFactory>;
    getContractAt(
      name: "IERC4337Account",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC4337Account>;
    getContractAt(
      name: "IERC7484",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC7484>;
    getContractAt(
      name: "IERC7579Account",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC7579Account>;
    getContractAt(
      name: "IMulticall3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMulticall3>;
    getContractAt(
      name: "INexus",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexus>;
    getContractAt(
      name: "INexusEventsAndErrors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INexusEventsAndErrors>;
    getContractAt(
      name: "IExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IExecutor>;
    getContractAt(
      name: "IFallback",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFallback>;
    getContractAt(
      name: "IHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHook>;
    getContractAt(
      name: "IModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IModule>;
    getContractAt(
      name: "IPreValidationHookERC1271",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPreValidationHookERC1271>;
    getContractAt(
      name: "IPreValidationHookERC4337",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPreValidationHookERC4337>;
    getContractAt(
      name: "IValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IValidator>;
    getContractAt(
      name: "AssociatedArrayLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AssociatedArrayLib>;
    getContractAt(
      name: "EnumerableMap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EnumerableMap>;
    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "ProxyLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProxyLib>;
    getContractAt(
      name: "Counter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Counter>;
    getContractAt(
      name: "EmittingHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EmittingHook>;
    getContractAt(
      name: "ExposedNexus",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExposedNexus>;
    getContractAt(
      name: "IExposedNexus",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IExposedNexus>;
    getContractAt(
      name: "Mock7739PreValidationHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Mock7739PreValidationHook>;
    getContractAt(
      name: "MockAccountLocker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockAccountLocker>;
    getContractAt(
      name: "MockCallee",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCallee>;
    getContractAt(
      name: "MockDelegateTarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDelegateTarget>;
    getContractAt(
      name: "MockExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockExecutor>;
    getContractAt(
      name: "MockHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHandler>;
    getContractAt(
      name: "MockHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHook>;
    getContractAt(
      name: "MockInvalidModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockInvalidModule>;
    getContractAt(
      name: "MockMultiModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockMultiModule>;
    getContractAt(
      name: "MockERC1155",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC1155>;
    getContractAt(
      name: "MockNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockNFT>;
    getContractAt(
      name: "MockPaymaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockPaymaster>;
    getContractAt(
      name: "MockPreValidationHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockPreValidationHook>;
    getContractAt(
      name: "MockPreValidationHookMultiplexer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockPreValidationHookMultiplexer>;
    getContractAt(
      name: "MockRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockRegistry>;
    getContractAt(
      name: "IAccount",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccount>;
    getContractAt(
      name: "IAccountLocker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccountLocker>;
    getContractAt(
      name: "MockResourceLockPreValidationHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockResourceLockPreValidationHook>;
    getContractAt(
      name: "MockSafe1271Caller",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockSafe1271Caller>;
    getContractAt(
      name: "MockSimpleValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockSimpleValidator>;
    getContractAt(
      name: "MockTarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockTarget>;
    getContractAt(
      name: "MockToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockToken>;
    getContractAt(
      name: "MockTransferer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockTransferer>;
    getContractAt(
      name: "MockValidator_7739v2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockValidator_7739v2>;
    getContractAt(
      name: "MockValidator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockValidator>;
    getContractAt(
      name: "IERC1271",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1271>;
    getContractAt(
      name: "TokenWithPermit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenWithPermit>;
    getContractAt(
      name: "AutoBridgeModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AutoBridgeModule>;
    getContractAt(
      name: "ISpokePool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISpokePool>;
    getContractAt(
      name: "IWrappedNative",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWrappedNative>;
    getContractAt(
      name: "AutoEarn",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AutoEarn>;
    getContractAt(
      name: "IAavePool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAavePool>;
    getContractAt(
      name: "IWrappedNative",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWrappedNative>;
    getContractAt(
      name: "AutoSwapModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AutoSwapModule>;
    getContractAt(
      name: "IQuoterV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IQuoterV2>;
    getContractAt(
      name: "ISwapRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISwapRouter>;
    getContractAt(
      name: "IWrappedNative",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWrappedNative>;
    getContractAt(
      name: "BondModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BondModule>;
    getContractAt(
      name: "K1Validator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.K1Validator>;
    getContractAt(
      name: "Nexus",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Nexus>;
    getContractAt(
      name: "NexusBootstrap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NexusBootstrap>;
    getContractAt(
      name: "NexusProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.NexusProxy>;
    getContractAt(
      name: "ERC7739Validator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC7739Validator>;
    getContractAt(
      name: "IERC5267",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC5267>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC4626",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC4626>;
    getContractAt(
      name: "SentinelListLib",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SentinelListLib>;
    getContractAt(
      name: "LibEIP7702",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LibEIP7702>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "CallContextChecker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CallContextChecker>;
    getContractAt(
      name: "ECDSA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ECDSA>;
    getContractAt(
      name: "EIP712",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EIP712>;
    getContractAt(
      name: "UUPSUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.UUPSUpgradeable>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1967",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IBeacon",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Utils",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Utils>;
    deployContract(
      name: "Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155>;
    deployContract(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155MetadataURI>;
    deployContract(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155>;
    deployContract(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Receiver>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Permit>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "Address",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECDSA>;
    deployContract(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Nonces",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nonces>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "ShortStrings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortStrings>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "BasePaymaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasePaymaster>;
    deployContract(
      name: "EntryPoint",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EntryPoint>;
    deployContract(
      name: "NonceManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NonceManager>;
    deployContract(
      name: "SenderCreator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SenderCreator>;
    deployContract(
      name: "StakeManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakeManager>;
    deployContract(
      name: "UserOperationLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UserOperationLib>;
    deployContract(
      name: "IAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccount>;
    deployContract(
      name: "IAccountExecute",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountExecute>;
    deployContract(
      name: "IAggregator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAggregator>;
    deployContract(
      name: "IEntryPoint",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEntryPoint>;
    deployContract(
      name: "INonceManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INonceManager>;
    deployContract(
      name: "IPaymaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymaster>;
    deployContract(
      name: "IStakeManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakeManager>;
    deployContract(
      name: "VerifyingPaymaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifyingPaymaster>;
    deployContract(
      name: "ComposableExecutionBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComposableExecutionBase>;
    deployContract(
      name: "ComposableExecutionLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComposableExecutionLib>;
    deployContract(
      name: "IComposableExecution",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IComposableExecution>;
    deployContract(
      name: "IComposableExecutionModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IComposableExecutionModule>;
    deployContract(
      name: "Storage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Storage>;
    deployContract(
      name: "BaseAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseAccount>;
    deployContract(
      name: "ExecutionHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExecutionHelper>;
    deployContract(
      name: "ModuleManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ModuleManager>;
    deployContract(
      name: "RegistryAdapter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RegistryAdapter>;
    deployContract(
      name: "Stakeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Stakeable>;
    deployContract(
      name: "BiconomyMetaFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BiconomyMetaFactory>;
    deployContract(
      name: "K1ValidatorFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.K1ValidatorFactory>;
    deployContract(
      name: "NexusAccountFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusAccountFactory>;
    deployContract(
      name: "IBiconomyMetaFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBiconomyMetaFactory>;
    deployContract(
      name: "IBondModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBondModule>;
    deployContract(
      name: "IMockToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMockToken>;
    deployContract(
      name: "IMulticall3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMulticall3>;
    deployContract(
      name: "INexusAccountFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusAccountFactory>;
    deployContract(
      name: "INexusBootstrap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusBootstrap>;
    deployContract(
      name: "IAccountConfig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountConfig>;
    deployContract(
      name: "IBaseAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBaseAccount>;
    deployContract(
      name: "IBaseAccountEventsAndErrors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBaseAccountEventsAndErrors>;
    deployContract(
      name: "IExecutionHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutionHelper>;
    deployContract(
      name: "IExecutionHelperEventsAndErrors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutionHelperEventsAndErrors>;
    deployContract(
      name: "IModuleManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModuleManager>;
    deployContract(
      name: "IModuleManagerEventsAndErrors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModuleManagerEventsAndErrors>;
    deployContract(
      name: "IStakeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakeable>;
    deployContract(
      name: "INexusFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusFactory>;
    deployContract(
      name: "IERC4337Account",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4337Account>;
    deployContract(
      name: "IERC7484",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7484>;
    deployContract(
      name: "IERC7579Account",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7579Account>;
    deployContract(
      name: "IMulticall3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMulticall3>;
    deployContract(
      name: "INexus",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexus>;
    deployContract(
      name: "INexusEventsAndErrors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusEventsAndErrors>;
    deployContract(
      name: "IExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutor>;
    deployContract(
      name: "IFallback",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFallback>;
    deployContract(
      name: "IHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHook>;
    deployContract(
      name: "IModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModule>;
    deployContract(
      name: "IPreValidationHookERC1271",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPreValidationHookERC1271>;
    deployContract(
      name: "IPreValidationHookERC4337",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPreValidationHookERC4337>;
    deployContract(
      name: "IValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IValidator>;
    deployContract(
      name: "AssociatedArrayLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AssociatedArrayLib>;
    deployContract(
      name: "EnumerableMap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EnumerableMap>;
    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "ProxyLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProxyLib>;
    deployContract(
      name: "Counter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Counter>;
    deployContract(
      name: "EmittingHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmittingHook>;
    deployContract(
      name: "ExposedNexus",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExposedNexus>;
    deployContract(
      name: "IExposedNexus",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExposedNexus>;
    deployContract(
      name: "Mock7739PreValidationHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mock7739PreValidationHook>;
    deployContract(
      name: "MockAccountLocker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAccountLocker>;
    deployContract(
      name: "MockCallee",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCallee>;
    deployContract(
      name: "MockDelegateTarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDelegateTarget>;
    deployContract(
      name: "MockExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockExecutor>;
    deployContract(
      name: "MockHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHandler>;
    deployContract(
      name: "MockHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHook>;
    deployContract(
      name: "MockInvalidModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockInvalidModule>;
    deployContract(
      name: "MockMultiModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockMultiModule>;
    deployContract(
      name: "MockERC1155",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC1155>;
    deployContract(
      name: "MockNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockNFT>;
    deployContract(
      name: "MockPaymaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPaymaster>;
    deployContract(
      name: "MockPreValidationHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPreValidationHook>;
    deployContract(
      name: "MockPreValidationHookMultiplexer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPreValidationHookMultiplexer>;
    deployContract(
      name: "MockRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockRegistry>;
    deployContract(
      name: "IAccount",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccount>;
    deployContract(
      name: "IAccountLocker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountLocker>;
    deployContract(
      name: "MockResourceLockPreValidationHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockResourceLockPreValidationHook>;
    deployContract(
      name: "MockSafe1271Caller",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSafe1271Caller>;
    deployContract(
      name: "MockSimpleValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSimpleValidator>;
    deployContract(
      name: "MockTarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTarget>;
    deployContract(
      name: "MockToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockToken>;
    deployContract(
      name: "MockTransferer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTransferer>;
    deployContract(
      name: "MockValidator_7739v2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockValidator_7739v2>;
    deployContract(
      name: "MockValidator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockValidator>;
    deployContract(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1271>;
    deployContract(
      name: "TokenWithPermit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenWithPermit>;
    deployContract(
      name: "AutoBridgeModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AutoBridgeModule>;
    deployContract(
      name: "ISpokePool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISpokePool>;
    deployContract(
      name: "IWrappedNative",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWrappedNative>;
    deployContract(
      name: "AutoEarn",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AutoEarn>;
    deployContract(
      name: "IAavePool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAavePool>;
    deployContract(
      name: "IWrappedNative",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWrappedNative>;
    deployContract(
      name: "AutoSwapModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AutoSwapModule>;
    deployContract(
      name: "IQuoterV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IQuoterV2>;
    deployContract(
      name: "ISwapRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapRouter>;
    deployContract(
      name: "IWrappedNative",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWrappedNative>;
    deployContract(
      name: "BondModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BondModule>;
    deployContract(
      name: "K1Validator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.K1Validator>;
    deployContract(
      name: "Nexus",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nexus>;
    deployContract(
      name: "NexusBootstrap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusBootstrap>;
    deployContract(
      name: "NexusProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusProxy>;
    deployContract(
      name: "ERC7739Validator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC7739Validator>;
    deployContract(
      name: "IERC5267",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IERC4626",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4626>;
    deployContract(
      name: "SentinelListLib",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SentinelListLib>;
    deployContract(
      name: "LibEIP7702",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LibEIP7702>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "CallContextChecker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CallContextChecker>;
    deployContract(
      name: "ECDSA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECDSA>;
    deployContract(
      name: "EIP712",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "UUPSUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeable>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1967",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1967>;
    deployContract(
      name: "IERC5267",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IBeacon",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBeacon>;
    deployContract(
      name: "ERC1967Utils",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1967Utils>;
    deployContract(
      name: "Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Proxy>;
    deployContract(
      name: "ERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC1155>;
    deployContract(
      name: "IERC1155MetadataURI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155MetadataURI>;
    deployContract(
      name: "IERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155>;
    deployContract(
      name: "IERC1155Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Receiver>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Permit>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "Address",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "ECDSA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECDSA>;
    deployContract(
      name: "EIP712",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "SafeCast",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeCast>;
    deployContract(
      name: "Nonces",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nonces>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "ShortStrings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ShortStrings>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "BasePaymaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasePaymaster>;
    deployContract(
      name: "EntryPoint",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EntryPoint>;
    deployContract(
      name: "NonceManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NonceManager>;
    deployContract(
      name: "SenderCreator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SenderCreator>;
    deployContract(
      name: "StakeManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakeManager>;
    deployContract(
      name: "UserOperationLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UserOperationLib>;
    deployContract(
      name: "IAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccount>;
    deployContract(
      name: "IAccountExecute",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountExecute>;
    deployContract(
      name: "IAggregator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAggregator>;
    deployContract(
      name: "IEntryPoint",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEntryPoint>;
    deployContract(
      name: "INonceManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INonceManager>;
    deployContract(
      name: "IPaymaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPaymaster>;
    deployContract(
      name: "IStakeManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakeManager>;
    deployContract(
      name: "VerifyingPaymaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifyingPaymaster>;
    deployContract(
      name: "ComposableExecutionBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComposableExecutionBase>;
    deployContract(
      name: "ComposableExecutionLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComposableExecutionLib>;
    deployContract(
      name: "IComposableExecution",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IComposableExecution>;
    deployContract(
      name: "IComposableExecutionModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IComposableExecutionModule>;
    deployContract(
      name: "Storage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Storage>;
    deployContract(
      name: "BaseAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BaseAccount>;
    deployContract(
      name: "ExecutionHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExecutionHelper>;
    deployContract(
      name: "ModuleManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ModuleManager>;
    deployContract(
      name: "RegistryAdapter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RegistryAdapter>;
    deployContract(
      name: "Stakeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Stakeable>;
    deployContract(
      name: "BiconomyMetaFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BiconomyMetaFactory>;
    deployContract(
      name: "K1ValidatorFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.K1ValidatorFactory>;
    deployContract(
      name: "NexusAccountFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusAccountFactory>;
    deployContract(
      name: "IBiconomyMetaFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBiconomyMetaFactory>;
    deployContract(
      name: "IBondModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBondModule>;
    deployContract(
      name: "IMockToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMockToken>;
    deployContract(
      name: "IMulticall3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMulticall3>;
    deployContract(
      name: "INexusAccountFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusAccountFactory>;
    deployContract(
      name: "INexusBootstrap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusBootstrap>;
    deployContract(
      name: "IAccountConfig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountConfig>;
    deployContract(
      name: "IBaseAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBaseAccount>;
    deployContract(
      name: "IBaseAccountEventsAndErrors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IBaseAccountEventsAndErrors>;
    deployContract(
      name: "IExecutionHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutionHelper>;
    deployContract(
      name: "IExecutionHelperEventsAndErrors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutionHelperEventsAndErrors>;
    deployContract(
      name: "IModuleManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModuleManager>;
    deployContract(
      name: "IModuleManagerEventsAndErrors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModuleManagerEventsAndErrors>;
    deployContract(
      name: "IStakeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IStakeable>;
    deployContract(
      name: "INexusFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusFactory>;
    deployContract(
      name: "IERC4337Account",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4337Account>;
    deployContract(
      name: "IERC7484",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7484>;
    deployContract(
      name: "IERC7579Account",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7579Account>;
    deployContract(
      name: "IMulticall3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMulticall3>;
    deployContract(
      name: "INexus",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexus>;
    deployContract(
      name: "INexusEventsAndErrors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INexusEventsAndErrors>;
    deployContract(
      name: "IExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExecutor>;
    deployContract(
      name: "IFallback",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFallback>;
    deployContract(
      name: "IHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHook>;
    deployContract(
      name: "IModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModule>;
    deployContract(
      name: "IPreValidationHookERC1271",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPreValidationHookERC1271>;
    deployContract(
      name: "IPreValidationHookERC4337",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPreValidationHookERC4337>;
    deployContract(
      name: "IValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IValidator>;
    deployContract(
      name: "AssociatedArrayLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AssociatedArrayLib>;
    deployContract(
      name: "EnumerableMap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EnumerableMap>;
    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "ProxyLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProxyLib>;
    deployContract(
      name: "Counter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Counter>;
    deployContract(
      name: "EmittingHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EmittingHook>;
    deployContract(
      name: "ExposedNexus",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExposedNexus>;
    deployContract(
      name: "IExposedNexus",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IExposedNexus>;
    deployContract(
      name: "Mock7739PreValidationHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mock7739PreValidationHook>;
    deployContract(
      name: "MockAccountLocker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockAccountLocker>;
    deployContract(
      name: "MockCallee",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCallee>;
    deployContract(
      name: "MockDelegateTarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDelegateTarget>;
    deployContract(
      name: "MockExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockExecutor>;
    deployContract(
      name: "MockHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHandler>;
    deployContract(
      name: "MockHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHook>;
    deployContract(
      name: "MockInvalidModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockInvalidModule>;
    deployContract(
      name: "MockMultiModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockMultiModule>;
    deployContract(
      name: "MockERC1155",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC1155>;
    deployContract(
      name: "MockNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockNFT>;
    deployContract(
      name: "MockPaymaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPaymaster>;
    deployContract(
      name: "MockPreValidationHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPreValidationHook>;
    deployContract(
      name: "MockPreValidationHookMultiplexer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockPreValidationHookMultiplexer>;
    deployContract(
      name: "MockRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockRegistry>;
    deployContract(
      name: "IAccount",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccount>;
    deployContract(
      name: "IAccountLocker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccountLocker>;
    deployContract(
      name: "MockResourceLockPreValidationHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockResourceLockPreValidationHook>;
    deployContract(
      name: "MockSafe1271Caller",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSafe1271Caller>;
    deployContract(
      name: "MockSimpleValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockSimpleValidator>;
    deployContract(
      name: "MockTarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTarget>;
    deployContract(
      name: "MockToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockToken>;
    deployContract(
      name: "MockTransferer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTransferer>;
    deployContract(
      name: "MockValidator_7739v2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockValidator_7739v2>;
    deployContract(
      name: "MockValidator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockValidator>;
    deployContract(
      name: "IERC1271",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1271>;
    deployContract(
      name: "TokenWithPermit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenWithPermit>;
    deployContract(
      name: "AutoBridgeModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AutoBridgeModule>;
    deployContract(
      name: "ISpokePool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISpokePool>;
    deployContract(
      name: "IWrappedNative",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWrappedNative>;
    deployContract(
      name: "AutoEarn",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AutoEarn>;
    deployContract(
      name: "IAavePool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAavePool>;
    deployContract(
      name: "IWrappedNative",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWrappedNative>;
    deployContract(
      name: "AutoSwapModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AutoSwapModule>;
    deployContract(
      name: "IQuoterV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IQuoterV2>;
    deployContract(
      name: "ISwapRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISwapRouter>;
    deployContract(
      name: "IWrappedNative",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWrappedNative>;
    deployContract(
      name: "BondModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BondModule>;
    deployContract(
      name: "K1Validator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.K1Validator>;
    deployContract(
      name: "Nexus",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Nexus>;
    deployContract(
      name: "NexusBootstrap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusBootstrap>;
    deployContract(
      name: "NexusProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.NexusProxy>;
    deployContract(
      name: "ERC7739Validator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC7739Validator>;
    deployContract(
      name: "IERC5267",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC5267>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "IERC4626",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC4626>;
    deployContract(
      name: "SentinelListLib",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SentinelListLib>;
    deployContract(
      name: "LibEIP7702",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LibEIP7702>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "CallContextChecker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CallContextChecker>;
    deployContract(
      name: "ECDSA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ECDSA>;
    deployContract(
      name: "EIP712",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EIP712>;
    deployContract(
      name: "UUPSUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.UUPSUpgradeable>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
